# Generated by Django 2.1.7 on 2021-09-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210921_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(help_text='200 characters or fewer', max_length=200),
        ),
    ]
