# Generated by Django 2.1.7 on 2021-10-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211012_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='n/a', help_text='City, State, Country', max_length=50),
        ),
    ]
