# Generated by Django 2.1.7 on 2022-01-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(help_text='200 characters or less', max_length=200),
        ),
    ]
