# Generated by Django 2.1.7 on 2022-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_notification_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='3k characters or less', max_length=3000),
        ),
    ]
