# Generated by Django 2.1.7 on 2022-10-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comment_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='ip_address',
            field=models.CharField(blank=True, default='00.000.000.000', max_length=25, null=True),
        ),
    ]
